词库自动化

diff --git a/.github/workflows/nightly-release.yml b/.github/workflows/nightly-release.yml
--- a/.github/workflows/nightly-release.yml
+++ b/.github/workflows/nightly-release.yml
@@ -42,7 +42,7 @@ jobs:
         with:
           python-version: "3.x"
 
-      # 5. 运行Python 脚本对 cn_dicts 进行处理，生成多个词库文件夹
+      # 5. 运行Python 脚本对 zh_dicts_pro 进行处理，生成多个词库文件夹
       - name: Process Rime dicts
         if: env.SKIP != 'true'
         run: |
@@ -50,17 +50,30 @@ jobs:
           pip install --upgrade pip
           python custom/万象分包.py
 
-      # 6. 打包原有的 cn_dicts 文件夹
-      - name: Pack cn_dicts
+      # 6. 打包原有的 zh_dicts_pro 文件夹
+      - name: Pack zh_dicts_pro
         if: env.SKIP != 'true'
         run: |
           mkdir -p dist
-          echo "Packing original cn_dicts..."
-          if [ -d "cn_dicts" ]; then
-            zip -r dist/8-cn_dicts.zip cn_dicts
-            echo "Packing completed: dist/8-cn_dicts.zip"
+          echo "Packing original zh_dicts_pro..."
+          if [ -d "zh_dicts_pro" ]; then
+            zip -r dist/8-pro-all-zh-dicts.zip zh_dicts_pro
+            echo "Packing completed: dist/8-pro-all-zh-dicts.zip"
           else
-            echo "Error: cn_dicts folder does not exist."
+            echo "Error: zh_dicts_pro folder does not exist."
+            exit 1
+          fi
+      # 7. 打包原有的 zh_dicts 文件夹
+      - name: Pack zh_dicts_pro
+        if: env.SKIP != 'true'
+        run: |
+          mkdir -p dist
+          echo "Packing original zh_dicts..."
+          if [ -d "zh_dicts" ]; then
+            zip -r dist/9-zh-dicts.zip zh_dicts
+            echo "Packing completed: dist/9-zh-dicts.zip"
+          else
+            echo "Error: zh_dicts_pro folder does not exist."
             exit 1
           fi
       # 7. 将拆分后的 8 个词库文件夹一并打包
@@ -71,13 +84,13 @@ jobs:
       
           # 定义文件夹 -> ZIP文件名的映射关系
           declare -A dict_map=(
-            ["moqi_dicts"]="1-moqi_dicts.zip"
-            ["flypy_dicts"]="2-flypy_dicts.zip"
-            ["zrm_dicts"]="3-zrm_dicts.zip"
-            ["jdh_dicts"]="4-jdh_dicts.zip"
-            ["tiger_dicts"]="5-tiger_dicts.zip"
-            ["wubi_dicts"]="6-wubi_dicts.zip"
-            ["hanxin_dicts"]="7-hanxin_dicts.zip"
+            ["pro-moqi-fuzhu-dicts"]="1-pro-moqi-fuzhu-dicts.zip"
+            ["pro-flypy-fuzhu-dicts"]="2-pro-flypy-fuzhu-dicts.zip"
+            ["pro-zrm-fuzhu-dicts"]="3-pro-zrm-fuzhu-dicts.zip"
+            ["pro-jdh-fuzhu-dicts"]="4-pro-jdh-fuzhu-dicts.zip"
+            ["pro-tiger-fuzhu-dicts"]="5-pro-tiger-fuzhu-dicts.zip"
+            ["pro-wubi-fuzhu-dicts"]="6-pro-wubi-fuzhu-dicts.zip"
+            ["pro-hanxin-fuzhu-dicts"]="7-pro-hanxin-fuzhu-dicts.zip"
           )
       
           mkdir -p dist
@@ -144,26 +157,28 @@ jobs:
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           tag_name: dict-nightly
-          name: "每夜构建-词库更新"
+          name: "实时词库更新"
           body: |
-            - **cn_dicts.zip**：最新的全辅助码原始中文词库文件
-            - **moqi_dicts.zip**：携带了墨奇辅助码的词库文件
-            - **flypy_dicts.zip**：携带了小鹤辅助码的词库文件
-            - **zrm_dicts.zip**：携带了自然码辅助码的词库文件
-            - **jdh_dicts.zip**：携带了简单鹤辅助码的词库文件
-            - **tiger_dicts.zip**：携带了虎码辅助码的词库文件
-            - **wubi_dicts.zip**：携带了五笔辅助码的词库文件
-            - **hanxin_dicts.zip**：携带了汉心辅助码的词库文件
+            - **zh-dicts.zip**：最新的标准版原始中文词库文件
+            - **pro-all-zh-dicts.zip**：最新的全辅助码原始中文词库文件
+            - **pro-moqi-fuzhu-dicts.zip**：携带了墨奇辅助码的词库文件
+            - **pro-flypy-fuzhu-dicts.zip**：携带了小鹤辅助码的词库文件
+            - **pro-zrm-fuzhu-dicts.zip**：携带了自然码辅助码的词库文件
+            - **pro-jdh-fuzhu-dicts.zip**：携带了简单鹤辅助码的词库文件
+            - **pro-tiger-fuzhu-dicts.zip**：携带了虎码辅助码的词库文件
+            - **pro-wubi-fuzhu-dicts.zip**：携带了五笔辅助码的词库文件
+            - **pro-hanxin-fuzhu-dicts.zip**：携带了汉心辅助码的词库文件
             - **[wanxiang-lts-zh-hans.gram](https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram)**：与词库同步更新的语法模型
           files: |
-            dist/8-cn_dicts.zip
-            dist/1-moqi_dicts.zip
-            dist/2-flypy_dicts.zip
-            dist/3-zrm_dicts.zip
-            dist/4-jdh_dicts.zip
-            dist/5-tiger_dicts.zip
-            dist/6-wubi_dicts.zip
-            dist/7-hanxin_dicts.zip
+            dist/9-zh-dicts.zip
+            dist/8-pro-all-zh-dicts.zip
+            dist/1-pro-moqi-fuzhu-dicts.zip
+            dist/2-pro-flypy-fuzhu-dicts.zip
+            dist/3-pro-zrm-fuzhu-dicts.zip
+            dist/4-pro-jdh-fuzhu-dicts.zip
+            dist/5-pro-tiger-fuzhu-dicts.zip
+            dist/6-pro-wubi-fuzhu-dicts.zip
+            dist/7-pro-hanxin-fuzhu-dicts.zip
             wanxiang-lts-zh-hans.gram
           draft: false
           prerelease: false
